# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0], but also installs the
# relevant version of LLVM as (a very old version of) the CUDA toolkit (4.0).
# Caches the 'stack' build directory to speed subsequent compilations.
#
language: generic
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.stack
    - $HOME/llvm

matrix:
  include:
    - env: GHC=7.8.4 CABAL=1.18 LLVM=3.5.2
      compiler: "GHC 7.8"
      addons:
        apt:
          sources:
            - hvr-ghc
            - ubuntu-toolchain-r-test
          packages:
            - nvidia-cuda-toolkit
            - g++-4.8
            - libgmp-dev
            - cabal-install-1.18
            - happy-1.19.5
            - alex-3.1.7
            - libhdf5-dev
            - libsilo-dev

    - env: GHC=7.10.3 CABAL=1.22 LLVM=3.9.0
      compiler: "GHC 7.10"
      addons:
        apt:
          sources:
            - hvr-ghc
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - nvidia-cuda-toolkit
            - g++-4.8
            - llvm-3.9-dev
            - libgmp-dev
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.7
            - libhdf5-dev
            - libsilo-dev

    - env: GHC=8.0.1 CABAL=1.22 LLVM=3.9.0
      compiler: "GHC 8.0"
      addons:
        apt:
          sources:
            - hvr-ghc
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - nvidia-cuda-toolkit
            - g++-4.8
            - llvm-3.9-dev
            - libgmp-dev
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.7
            - libhdf5-dev
            - libsilo-dev

  fast_finish: true

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  - |
      case ${GHC} in
        7.8.*) export UPGRADE_CABAL=1 ;;
      esac
  - source .travis/install-stack.sh
  - |
      case ${LLVM} in
        3.5.*) source .travis/install-llvm-trusty.sh ;;
      esac
  - source .travis/update-ghc-settings.sh

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - llc --version; true
  - opt --version; true
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        travis_retry cabal install --only-dependencies
      else
        travis_retry stack build --only-dependencies --no-terminal --no-haddock-deps
      fi

script:
  - |
      if [ ${GHC} == head -o ! -e stack.yaml ]; then
        cabal install
        cabal haddock
      else
        stack build --no-terminal --haddock --no-haddock-deps --flag lulesh-accelerate:visit
      fi

after_success:
  - source .travis/update-accelerate-buildbot.sh

