# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0], but also installs the
# relevant version of LLVM as (a very old version of) the CUDA toolkit (4.0).
# Caches the 'stack' build directory to speed subsequent compilations.
#
language: minimal
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

# before_cache:
#   - rm -rf $(stack path --local-install-root)/bin/lulesh-accelerate
#   - rm -rf $(stack path --local-install-root)/doc

matrix:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0

    packages: &apt_packages
      - alex-3.1.4
      - g++-4.8
      - happy-1.19.5
      - libgmp-dev
      - libhdf5-openmpi-dev
      - libsilo-dev
      - libsiloh5-0

  include:
    - env: GHC=7.10.3 CABAL=1.22 LLVM-5.0.0 CUDA=8.0.61-1
      compiler: "GHC 7.10"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-1.22
            - llvm-5.0-dev

    - env: GHC=8.0.2 CABAL=1.24 LLVM-5.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.0"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-1.24
            - llvm-5.0-dev

    - env: GHC=8.2.2 CABAL=2.0 LLVM-5.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.2"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-2.0
            - llvm-5.0-dev

    - env: GHC=8.4.1 CABAL=2.0 LLVM-6.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.4"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-2.0
            - llvm-6.0-dev

  fast_finish: true

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  # - |
  #     case ${GHC} in
  #       7.8.*) export UPGRADE_CABAL=1 ;;
  #     esac
  # - |
  #     case ${LLVM} in
  #       3.5.*) source .travis/install-llvm-trusty.sh ;;
  #     esac
  # - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh
  - travis_retry stack install c2hs --fast --no-terminal

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - llc --version; true
  - opt --version; true
  - stack build --dry-run
  - travis_retry stack build --only-dependencies --fast --jobs=2 --no-terminal --no-haddock-deps --flag lulesh-accelerate:-llvm-gpu --flag lulesh-accelerate:visit

script:
  - stack build --fast --jobs=2 --no-terminal --haddock --no-haddock-deps --flag lulesh-accelerate:-llvm-gpu --flag lulesh-accelerate:visit

after_success:
  - source .travis/update-accelerate-buildbot.sh

